### ISSUE TITLE
Pixi binary not found for linux running on M1 Mac

### ISSUE THREAD

**Issue by christianlangevin** [mjr-deltares/parallel-modflow-dsd23#3]
Just an FYI that pixi did not work for me out of the box when running Ubuntu 22.04 on a Parallels virtual machine on a Mac M1.  I did get everything to work by first installing the correct version of pixi for this platform by running:

```
curl -fsSL https://pixi.sh/install.sh | bash
```

I then had to modify pixi.toml to include the "linux-aarch64" architecture as shown below.

```
[project]
name = "mf6xtd"
version = "1.0.0"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "linux-aarch64"]
...
```

Lastly, I ran `pixi run installation` and `pixi run jupyter` instead of `./pixi run installation` and `./pixi run jupyter` so that it ran my installed pixi version.

I know my configuration is fairly abnormal.  But it did eventually work with this changes, and I could run the parallel test included in ./installation/test_installation.ipynb.

Pretty slick.

**Comment by mjr-deltares** [comment]
I think this can be closed, no?
