### ISSUE TITLE
Update installation instructions for Mac and Linux

### ISSUE THREAD

**Issue by pya** [mjr-deltares/parallel-modflow-dsd23#5]
The README.md says:

_If you are using the MacOS or Linux operating system you can follow the instructions in [wsl_setup.md](https://github.com/mjr-deltares/parallel-modflow-dsd23/blob/main/wsl_setup.md) starting at the [Installing_Miniconda section](https://github.com/mjr-deltares/parallel-modflow-dsd23/blob/main/wsl_setup.md#installing-miniconda)._

But the section `#installing-miniconda` does **not** exist. Also, the setup seems to use `pixie` instead of `conda` now.  Can you update the installation instructions for Max and Linux. Likely an installation of `pixi` is required.

**Comment by mjr-deltares** [comment]
Thanks @pya for trying out the Linux/Mac route. I have updated the instructions, you should be able to follow them starting from "Clone the class repo" (we had renamed that section...)

**Comment by pya** [comment]
Thanks @mjr-deltares. Worked like a charm and completed all steps. It says:

    Host machine cpu family: x86_64
    Host machine cpu: x86_64

But I am on an M1 Macbook. Looks like it did not recognize that `arm64` would be the better choice.

**Comment by mjr-deltares** [comment]
Excellent. Appreciate the feedback and maybe we can have a look at your arm64 issue next week? Looking forward.
